version: 1
config:
  target: "http://0.0.0.0:8000"
  phases:
    - duration: 20
      arrivalRate: 1000
  processor: "./processor.js"
scenarios:
  - flow:
      - function: "generatePayload"
      - post:
          url: "/api/v1/message"
          json: "{{ payload }}"
          headers:
            content-type: "application/json"
